version: "3.9"

services:
  webdev_laravel:
    image: webdev_laravel
    container_name: webdev_laravel
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./webdev_projet_laravel:/var/www/webdev_projet_laravel
    depends_on:
      - db
    networks:
      - webdev-laravel-net

  db:
    image: mariadb:latest
    container_name: database
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: webdev-laravel
      MYSQL_DATABASE: webdev
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - webdev-laravel-net

networks:
  webdev-laravel-net:
    driver: bridge
